### ISSUE TITLE
关于dart的问题

### ISSUE THREAD

**Issue by miludexiuxianshaonv** [kexin0614/fwmav_sim_sjtu#1]
您好，我之前一直在尝试安装flappy程序，在安装dart和pydart2中遇到了一些问题。所以想请教一下您
1、请问要是想运行您的程序，不需要安装pyart2吗？
2、关于您在flappy程序中的回复，我想请问安装软件都是在虚拟环境中吗？
3、关于pydart2您的成功安装方法，我想问我可以在git clone https://github.com/sehoonha/pydart2.git之后直接在终端中敲命令修改C++吗？
期待您的回复，也将我的邮箱告诉您。我的邮箱是18120283@bjtu.edu.cn。期望能够得到您的指点。

**Comment by kexin0614** [comment]
噢噢你好，不好意思假期在家上github太慢了，就没管消息
1我这个仓库只是假期前上传备份的，没怎么测试，不过这个和Python无关，因为是直接用C++写的，装了DART和Eigen库应该就能用
2对，用虚拟环境只是确保和其它程序不相互干扰，不过这个pydart2我记得当时可能是全局安装的，因为是从源码编译安装
3克隆下来以后根目录不是有个setup.py么，用文本编辑器改一下里面33行的C++flag
要是有问题的话你可以发邮件给我kexin0614@sjtu.edu.cn，这个issue我关了哈
